apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: newrelic-auth
  namespace: default
spec:
  metadata:
    accountId: "6225327"     # Replace with your Account ID
    queryKey: "NRAK-OD9DAW51YAW7LVC5CP5G67245T8"       # Replace with your Query Key
