apiVersion: apps/v1
kind: Deployment
metadata:
  name: devfest-prediction-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devfest-prediction-api
  template:
    metadata:
      labels:
        app: devfest-prediction-api
    spec:
      containers:
        - name: flask-api
          image: your-docker-image:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devfest-prediction-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: devfest-prediction-api
