apiVersion: apps/v1
kind: Deployment
metadata:
  name: devfest-app-2024
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devfest-app-2024
  template:
    metadata:
      labels:
        app: devfest-app-2024
    spec:
      containers:
      - name: devfest-app-2024
        image: ghcr.io/chamodshehanka/argocd-demo:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-secret
              key: licenseKey
