apiVersion: v1
kind: Service
metadata:
  name: devfest-app-2024
  namespace: default
spec:
  selector:
    app: devfest-app-2024
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer